'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GeneratorControlLibrary.Resource", GetType(Resource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Username und Password are Empty ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strErrorLogin() As String
            Get
                Return ResourceManager.GetString("strErrorLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Username or Password are  invalid ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strLoginfalse() As String
            Get
                Return ResourceManager.GetString("strLoginfalse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die you must enter a Username ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StrNoText() As String
            Get
                Return ResourceManager.GetString("StrNoText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die All Question are correct. password has been succefully reset. please login with your new password ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strPasswordDelete() As String
            Get
                Return ResourceManager.GetString("strPasswordDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The Password ist not confirm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strPasswordNoConfirm() As String
            Get
                Return ResourceManager.GetString("strPasswordNoConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die you must enter a User_Id ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strTextBoxEmpty() As String
            Get
                Return ResourceManager.GetString("strTextBoxEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;Would you like to close the application?&quot; ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strUserControlExit() As String
            Get
                Return ResourceManager.GetString("strUserControlExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die the Data ist deleted ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strUserDelete() As String
            Get
                Return ResourceManager.GetString("strUserDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die your login information has been successfully and you can open now the application ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strUserLogin() As String
            Get
                Return ResourceManager.GetString("strUserLogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die you are registered online  System ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strUserRegister() As String
            Get
                Return ResourceManager.GetString("strUserRegister", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Username und Password are changed ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property strUserUpdate() As String
            Get
                Return ResourceManager.GetString("strUserUpdate", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
